# Generated by Django 3.1.2 on 2020-11-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='apellido',
        ),
        migrations.AddField(
            model_name='empleados',
            name='salario',
            field=models.FloatField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
